name: Call Build Repo Listing

on:
    workflow_dispatch:
    workflow_run:
        workflows: [Build Release]
        types:
            - completed

permissions:
    contents: read

jobs:
    build-listing:
        uses: jf9tgl/vpm-list/.github/workflows/call-build-listing.yml@main
        secrets:
            DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
